### ISSUE TITLE
你好，麻烦可以给我发一下你现在的那个主题文件夹吗，我想参考一下评论区的配置

### ISSUE THREAD

**Issue by geek-player** [DID321/did321.github.io#1]
你好，麻烦可以给我发一下你现在的那个主题文件夹吗，我想参考一下评论区的配置

**Comment by DID321** [comment]
你好，我已经在B站私信你了，配置评论区，只需要在\themes\hexo-theme-Chic\layout\_page 文件夹下的post.js&nbsp;
里面配置Valine，





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DID321/did321.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月26日(星期四) 凌晨3:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[DID321/did321.github.io] 你好，麻烦可以给我发一下你现在的那个主题文件夹吗，我想参考一下评论区的配置 (#1)





 
你好，麻烦可以给我发一下你现在的那个主题文件夹吗，我想参考一下评论区的配置
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
